language: node_js

node_js:
  - 0.6

after_install:
  - sudo npm install -g phantomjs
  - sudo npm install -g testem

before_script:
  - phantomjs --version
  - jasmine-node --coffee spec

script: node_modules/.bin/testem ci